1
mate-academy/js_task-move-spider-DOM pull request #388
Opened 2021-10-31 08:43 UTC by serhii-dvorets

https://serhii-dvorets.github.io/js_task-move-spider-DOM/

2021-11-01 11:01 UTC, vkryvytskyy requested changes

2021-11-01 11:01 UTC, vkryvytskyy commented on src/scripts/main.js
> +  }
Две одинаковые функции, думаю можно сделать одну, которая будет принимать point и x или y, и в зависимости от этого будет подставлять нужное значение в if

2021-11-03 18:42 UTC, vkryvytskyy requested changes

2021-11-03 18:42 UTC, vkryvytskyy commented on src/scripts/main.js
> +    }
У тебя тут все ще повторяется один и тот же код два раза, сделай так, чтобы не надо было писать одно и то же дважды

2021-11-05 12:40 UTC, varseniuk approved these changes

2024-05-11 11:36 UTC, closed without merging