Solution
mate-academy/js_task-move-spider-DOM pull request #435
Opened 2022-04-06 12:43 UTC by YevgeniySavchuk

[DEMO LINK](https://YevgeniySavchuk.github.io/js_task-move-spider-DOM/)

2022-04-06 13:13 UTC, YevgeniySavchuk commented
Подправил решение на случай если изменятся размеры стены или паука.

2022-04-07 07:15 UTC, Bohdan-Maksymiuk requested changes
Use separate variables for this, for example:
```
  let y = e.offsetY - spider.clientWidth / 2;
  let x = e.offsetX - spider.clientHeight / 2;

  const yWall = wall.clientHeight - spider.clientHeight;
  const xWall = wall.clientWidth - spider.clientWidth;
  ```
  then you could compare what you need and add styles
  there are a lot of repeated logic in your code

2022-04-07 09:12 UTC, YevgeniySavchuk commented
В тестах проваливается run npm install (и это не первый раз) - что это значит и что с этим делать?

2022-04-07 09:20 UTC, ArtemTopolskyi approved these changes
По поводу тестов - это не критично

2022-04-07 15:35 UTC, closed without merging